<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-56HO2UA" failures="1" tests="1" name="OwnerLoginPage.Generic_OwnerapartmentRoomRegTest" time="2.641" errors="0" timestamp="2023-11-23T15:37:55 IST" skipped="0">
  <testcase classname="OwnerLoginPage.Generic_OwnerapartmentRoomRegTest" name="OwnerapartmentRoomRegTest" time="2.641">
    <failure message="expected not same" type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError: expected not same
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failSame(Assert.java:276)
at junit.framework.Assert.assertNotSame(Assert.java:262)
at junit.framework.Assert.assertNotSame(Assert.java:269)
at com.ObjectRepo.OwnerHomePage.checkCount(OwnerHomePage.java:82)
at OwnerLoginPage.Generic_OwnerapartmentRoomRegTest.OwnerapartmentRoomRegTest(Generic_OwnerapartmentRoomRegTest.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- OwnerapartmentRoomRegTest -->
  <system-out>
OwnerapartmentRoomRegTest---TestScript execution starts from here OwnerapartmentRoomRegTest---TestScript execution starts from here OwnerapartmentRoomRegTest23/11/2023 15-37-53----Testscript execution failed OwnerapartmentRoomRegTest23/11/2023 15-37-53----Testscript execution failed  </system-out>
</testsuite> <!-- OwnerLoginPage.Generic_OwnerapartmentRoomRegTest -->
